import fs from 'fs'
import path from 'path'
import type { RunReport, CheckResult } from './types.js'

function statusBadge(result: CheckResult): string {
  return result.status === 'ok'
    ? '<span class="badge ok">✓ OK</span>'
    : '<span class="badge fail">✗ FAIL</span>'
}

function row(result: CheckResult): string {
  return `
    <tr class="${result.status}">
      <td>${statusBadge(result)}</td>
      <td>${result.name}</td>
      <td><a href="${result.url}" target="_blank">${result.url}</a></td>
      <td>${result.statusCode ?? '—'}</td>
      <td>${result.durationMs}ms</td>
      <td>${result.error ?? '—'}</td>
      <td>${result.screenshotPath ? `<a href="${result.screenshotPath}">view</a>` : '—'}</td>
    </tr>`
}

export function generateReport(report: RunReport, outputDir: string): string {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Monitor Report — ${report.ranAt}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #111; }
    h1 { font-size: 1.4rem; }
    .summary { display: flex; gap: 1.5rem; margin: 1rem 0 2rem; }
    .stat { background: #f4f4f4; border-radius: 8px; padding: 0.75rem 1.25rem; }
    .stat span { font-size: 1.5rem; font-weight: 700; display: block; }
    .stat.fail span { color: #d00; }
    .stat.ok span { color: #080; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; border-bottom: 2px solid #ddd; padding: 0.5rem; font-size: 0.8rem; text-transform: uppercase; color: #666; }
    td { padding: 0.6rem 0.5rem; border-bottom: 1px solid #eee; font-size: 0.9rem; }
    tr.fail td { background: #fff5f5; }
    .badge { padding: 2px 8px; border-radius: 4px; font-weight: 600; font-size: 0.8rem; }
    .badge.ok { background: #e6f9ee; color: #080; }
    .badge.fail { background: #fde8e8; color: #d00; }
    footer { margin-top: 3rem; font-size: 0.75rem; color: #999; text-align: center; }
    footer a { color: #999; }
  </style>
</head>
<body>
  <h1>Monitor Report</h1>
  <p>Run at: ${report.ranAt}</p>
  <div class="summary">
    <div class="stat ok"><span>${report.passed}</span>Passed</div>
    <div class="stat fail"><span>${report.failed}</span>Failed</div>
    <div class="stat"><span>${report.results.length}</span>Total</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Status</th><th>Name</th><th>URL</th><th>Code</th><th>Duration</th><th>Error</th><th>Screenshot</th>
      </tr>
    </thead>
    <tbody>
      ${report.results.map(row).join('')}
    </tbody>
  </table>
  <footer>
    Generated by <a href="https://monitor.alosha.dev">@alosha/monitor</a> — Built by <a href="https://alosha.dev">Alosha</a>
  </footer>
</body>
</html>`

  fs.mkdirSync(outputDir, { recursive: true })
  const outPath = path.join(outputDir, 'monitor-report.html')
  fs.writeFileSync(outPath, html, 'utf-8')
  return outPath
}
